# Generated by Django 3.0.7 on 2020-06-04 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_stock_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 14, 50, 1, 625560, tzinfo=utc)),
        ),
    ]
