# Generated by Django 3.0.7 on 2020-07-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200729_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='order',
            name='item_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
