# Generated by Django 3.0.7 on 2020-07-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200730_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='fake', max_length=10),
            preserve_default=False,
        ),
    ]
