# Generated by Django 3.0.7 on 2020-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=2000)),
                ('total_item_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.CharField(max_length=1000)),
                ('delivery_type', models.CharField(max_length=200)),
                ('delivery_amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_order_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('s_quantity', models.PositiveIntegerField()),
                ('m_quantity', models.PositiveIntegerField()),
                ('l_quantity', models.PositiveIntegerField()),
                ('xl_quantity', models.PositiveIntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
