# Generated by Django 3.0.7 on 2020-06-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200604_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='pub_date',
        ),
    ]
