# Generated by Django 3.0.7 on 2020-06-04 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orders_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=2000)),
                ('total_item_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.CharField(max_length=1000)),
                ('delivery_type', models.CharField(max_length=200)),
                ('delivery_amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_order_value', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 6, 4, 15, 24, 50, 212824, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
